name: rocq

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  prove:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: rocq-prover/docker-opam-action@126d4ac196f8133729a1cb0d2aa1ee7106efec58 # v1.5.2
        with:
          custom_image: rocq/rocq-prover:9.1
          custom_script: |
            mkdir -p /tmp/rocq
            # Assume .v files are independent.
            # Do not check admits in the module's dependencies.
            for file in rocq/*.v; do
              module="$(basename "$file" .v)"
              rocq compile -noglob -o "/tmp/rocq/$module.vo" "$file"
              if rocq check -silent --output-context "/tmp/rocq/$module.vo" 2>&1 | grep -F "    $module."; then
                exit 1
              fi
            done
